module.exports = {
    "up": "CREATE TABLE products (id INT NOT NULL AUTO_INCREMENT, UNIQUE KEY id (id), name VARCHAR (255) NOT NULL, descriptions text (1000) NOT NULL, price VARCHAR (255) NOT NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)",
    "down": "TRUNCATE TABLE  products"
}